# This program draws 6 different shapes
import turtle

# Set the window size.
turtle.setup(400, 600)

# Setup the turtle.
turtle.penup()
turtle.hideturtle()

# Create name constants for figure TL. 
TL_TL = (-150, 275)
TL_TR = (-50, 275)
TL_ML = (-200, 225)
TL_MM = (-100, 225)
TL_MR = (0, 225)
TL_BL = (-150, 175)
TL_BR = (-50, 175)

# Create name constants for figure TR.
TR_T = (100, 280)
TR_M = (100, 225)
TR_L = (50, 170)
TR_R = (150, 170)

# Create name constants for figure ML.
ML_TL = (-160, 60)
ML_TR = (-100, 60)
ML_ML = (-160, 0)
ML_MM = (-100, 0)
ML_MR = (-40, 0)
ML_BL = (-100, -60)
ML_BR = (-40, -60)

# Create name constants for figure MR.
MR_A = (50, -12.5)
MR_B = (75, -35)
MR_C = (100, -12.5)
MR_D = (125, -35)
MR_E = (150, -12.5)

# Create name constants for figure BL.
BL_N = (-100, -140)
BL_W = (-170, -210)
BL_M = (-100, -210)
BL_E = (-30, -210)
BL_S = (-100, -280)

# Create name constants for figure BR. 
BR_TL = (30, -140)
BR_TR = (170, -140)
BR_MM = (100, -210)
BR_BL = (30, -280)
BR_BR = (170, -280)

# Connect the lines to coordinates for figure TL.
turtle.goto(TL_TL)
turtle.pendown()
turtle.goto(TL_MM)
turtle.goto(TL_BR)
turtle.goto(TL_MR)
turtle.goto(TL_TR)
turtle.goto(TL_MM)
turtle.goto(TL_BL)
turtle.goto(TL_ML)
turtle.goto(TL_TL)
turtle.penup()

# Connect the lines to coordinates for figure TR.
turtle.goto(TR_L)
turtle.pendown()
turtle.goto(TR_T)
turtle.goto(TR_R)
turtle.goto(TR_M)
turtle.goto(TR_L)
turtle.goto(TR_R)
turtle.penup()

# Connect the lines to coordinates for figure ML.
turtle.goto(ML_ML)
turtle.pendown()
turtle.goto(ML_TL)
turtle.goto(ML_TR)
turtle.goto(ML_MR)
turtle.goto(ML_BR)
turtle.goto(ML_BL)
turtle.goto(ML_ML)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_BL)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_BL)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_BR)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_MR)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_TR)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_TL)
turtle.penup()
turtle.goto(ML_MM)
turtle.pendown()
turtle.goto(ML_ML)
turtle.penup()

# Connect the lines to coordinates for figure MR.
turtle.goto(MR_A)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(MR_B)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(MR_C)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(MR_D)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(MR_E)
turtle.pendown()
turtle.circle(20)
turtle.penup()

# Connect the lines to coordinates for figure BL.
turtle.goto(BL_N)
turtle.pendown()
turtle.goto(BL_M)
turtle.goto(BL_S)
turtle.penup()
turtle.goto(BL_W)
turtle.pendown()
turtle.goto(BL_M)
turtle.goto(BL_E)
turtle.penup()
turtle.goto(-100, -225)
turtle.pendown()
turtle.circle(15)
turtle.penup()
turtle.goto(-25, -217)
turtle.write('East')
turtle.goto(-112, -135)
turtle.write('North')
turtle.goto(-112, -300)
turtle.write('South')
turtle.goto(-200, -217)
turtle.write('West')

# Connect the lines to coordinates for figure BR.
turtle.goto(BR_TL)
turtle.pendown()
turtle.dot()
turtle.goto(BR_BL)
turtle.dot()
turtle.goto(BR_MM)
turtle.dot()
turtle.goto(BR_BR)
turtle.dot()
turtle.goto(BR_TR)
turtle.dot()
turtle.goto(BR_MM)
turtle.goto(BR_TL)
turtle.dot()
turtle.forward(16)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(16)
turtle.penup()
turtle.goto(BR_BL)
turtle.pendown()
turtle.forward(16)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.forward(16)
turtle.pendown()
turtle.forward(16)
turtle.done()
